### ISSUE TITLE
Ticking closed PRs

### ISSUE THREAD

**Issue by binaryberry** [emmabeynon/github-trello-poster#37]
At the moment, when PRs are merged, this app updates the Trello card by ticking the PR in the Trello card checklist, which also strikes it through and greys it out.

It would be great if it could do that when PRs close as well.

**Comment by emmabeynon** [comment]
Thanks for this suggestion @binaryberry - this has now been addressed in https://github.com/emmabeynon/github-trello-poster/pull/49 👍
