### ISSUE TITLE
Don't add the PR more than once

### ISSUE THREAD

**Issue by h-lame** [emmabeynon/github-trello-poster#41]
In some of our cards we've been annotating the list of PRs to explain what purpose they serve, and once we do that then the trello poster will re-add the PR as an item to the list without the annotation.

See: 
<img width="565" alt="example trello card with annotated prs" src="https://cloud.githubusercontent.com/assets/608/23256031/b46622e4-f9b5-11e6-9707-ee2c13b684ca.png">
the PR for https://github.com/alphagov/frontend/pull/1035 has been added twice, once at the top (and subsequently annotated) and then again at the bottom.

It'd be nice if it understood that the PR was in the list already when it'd been annotated and didn't duplicate it.

(Full disclosure - we weren't using the trello poster when the PRs were originally added, we are now so maybe that;s why they're being duplicated?)

**Comment by emmabeynon** [comment]
Hi @h-lame - thanks for the suggestion. I've now made a fix and will deploy it in a couple of weeks when I'm back from holiday, so I can keep an eye out for any issues 👍
